paths:
  raw_data: "data/raw/<ISO3>"
  intermediate_data: "data/intermediate/<ISO3>"
  final_data: "data/final"
  predictions: "data/final/predictions"
  logs: "logs"
  models: "models"
  cache: "cache"
